### PR TITLE
Style.css on every page & CSS changes

### PR DESCRIPTION
**Pull request by mattregul**
- Added styles.css to render_list.cpp :: render_list()
- CSS changes:
- - Set Font to Verdana, Verdana, Geneva, sans-serif
- - Hyperlinks aren't underlined by default (text-decoration: none)
- - Hovering mouse over hyperlink will underline it

### CODE REVIEW

**Comment by BenLubar** [comment]
Why is `Verdana` listed twice?

**Comment by mattregul** [comment]
Actually, it's not needed twice.  I just copy/pasted from http://www.ampsoft.net/webdesign-l/WindowsMacFonts.html.  I was trying to ensure it ensure it looks the same on Windows and Mac (and Linux?)

**Comment by mattregul** [comment]
I can pull it out, and also fix the extra line break that CodeFactor is mentioning

**Comment by BenLubar** [comment]
If the intention is to make it use the same font on all OSes, we can just embed an open source one from Google Fonts.

Here's a bunch in the same basic shape as Verdana: https://fonts.google.com/?category=Sans+Serif&thickness=5&width=7&slant=1

**Comment by mattregul** [comment]
How's this? - https://fonts.google.com/specimen/Varela+Round
I went with this one as it's still easy to read with small print.
image

**Pull request merged**
